# Generated by Django 4.0.6 on 2022-07-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=255)),
                ('Fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Join_date', models.DateField()),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.course')),
            ],
        ),
    ]
