# Generated by Django 4.0.6 on 2022-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_student_phone_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='Image',
            field=models.ImageField(default=1, upload_to='image/tutor'),
            preserve_default=False,
        ),
    ]
