# Generated by Django 4.0.6 on 2022-08-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_tutor_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='image/tutor'),
        ),
    ]
